### PR TITLE
Added missing roslog format

### PR DESCRIPTION
**Pull request by BenStarmerSmith**
## Proposed changes

Added missing roslog format to NUC and GUI icons.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [x] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [x] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

### CODE REVIEW

**Comment by maxzieba** [comment]
have tested if adding these lines in .bashrc would result in a similar result?

**Comment by BenStarmerSmith** [comment]
> have tested if adding these lines in .bashrc would result similarly?

I haven't, this was just a bug to make sure we were doing this uniformly. As this is how we were doing it in all Icons but the GUI. However, this would be an excellent solution and solve this problem, so I will add it to the tech debt report of Aurora :smile:

**Comment by BenStarmerSmith** [comment]
Screenshot from 2022-11-28 14-28-49
Before

**Comment by BenStarmerSmith** [comment]
Screenshot from 2022-11-28 14-22-20
After

**Review by georgiablanco — APPROVED** [review]

**Comment by maxzieba** [comment]
Can't spot the difference between before and after. Where's the difference?

**Review by carebare47 — CHANGES_REQUESTED** [review]
This is already in our .bashrc? At least the first bit:
```
export ROSCONSOLE_FORMAT='"'[${severity}](${node}): [${time}] ${message}'"'
```
is put in by this: https://github.com/shadow-robot/sr-build-tools/blob/5d77b310323b1c8956a8d508f2886c3bce6c9e9c/docker/utils/additional_bashrc_cmds_noetic#L73
right?

**Comment by carebare47** [comment]
> This is already in our .bashrc? At least the first bit:
> 
> ```
> export ROSCONSOLE_FORMAT='"'[${severity}](${node}): [${time}] ${message}'"'
> ```
> 
> is put in by this: https://github.com/shadow-robot/sr-build-tools/blob/5d77b310323b1c8956a8d508f2886c3bce6c9e9c/docker/utils/additional_bashrc_cmds_noetic#L73 right?

Cause found, tech debt added to dev-ops to-do list. Approving this fix for now

**Review by carebare47 — APPROVED** [review]

**Pull request merged**
